namespace SpriteKind {
    export const happy = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    key_card = 1
    tiles.setTileAt(location, sprites.vehicle.roadHorizontal)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorClosedNorth, function (sprite, location) {
    if (key_card == 1) {
        tiles.setTilemap(tilemap`the lair`)
    } else {
        game.splash("you need to find the key card first")
        chris.y += 2
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`happy coins`, function (sprite, location) {
    info.changeLifeBy(1)
    tiles.setTileAt(location, sprites.vehicle.roadTurn2)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    otherSprite.destroy()
})
let chris: Sprite = null
let key_card = 0
key_card = 0
info.startCountdown(50)
tiles.setTilemap(tilemap`level1`)
info.setLife(4)
chris = sprites.create(assets.image`chris`, SpriteKind.Player)
let small = sprites.create(assets.image`beta henchman`, SpriteKind.Enemy)
let biggie_smalls = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff8888ff........
    .......fb888888bf.......
    .......f88888888f.......
    ......fd88888888df......
    ......fd88888888df......
    ......fddd8888dddf......
    ......fbdbfddfbdbf......
    ......fcdce884cdcf......
    .......fb888888bf.......
    ......fffcdb8bdffff.....
    ....fc888cbfbfc888cf....
    ....f8b8b8ffff8b8b8f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
let dez = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ffaaaaff........
    .......fbaaaaaabf.......
    .......faaaaaaaaf.......
    ......fdaaaaaaaadf......
    ......fdaaaaaaaadf......
    ......fdddaaaadddf......
    ......fbdbfddfbdbf......
    ......fcdc7aa6cdcf......
    .......fbaaaaaabf.......
    ......fffcdbabdffff.....
    ....fcaaacbfbfcaaacf....
    ....fababaffffababaf....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
let candice = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    .........ff3f3ff........
    ........33f33ffbf.......
    .......3f33fff77f.......
    .......3ffff7777df......
    ......fffff77777df......
    ......fddd7777dddf......
    ......fbdbfddfbdbf......
    ......fcdc5772cdcf......
    .......fb777777bf.......
    ......fffcdb7bdffff.....
    ....fc777cbfbfc777cf....
    ....f7b7b7ffff7b7b7f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
sprites.create(img`
    ....ff..................
    ...fd1f............ffff.
    ...fdd1ff.........ff1df.
    ...fdd111f.......ff11dff
    ...fdddd11ffffffff1dddf.
    ...ffddd1d111f1111bddff.
    ....fddd111fff1ddbddff..
    ....ffdd111f1111d1dff...
    .....ffd11111111ddff....
    ......fd11111111dff.....
    ......fddd1111dddf......
    ......fbdf2ddf2dbf......
    ......fcd2f112fdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy).setVelocity(50, 50)
candice.setVelocity(50, 50)
dez.setVelocity(50, 50)
biggie_smalls.follow(chris)
candice.follow(chris)
dez.follow(chris)
small.follow(chris)
biggie_smalls.setVelocity(50, 50)
small.setVelocity(50, 50)
tiles.placeOnRandomTile(chris, sprites.dungeon.stairLadder)
tiles.placeOnTile(chris, tiles.getTileLocation(8, 0))
scene.cameraFollowSprite(chris)
tiles.placeOnRandomTile(biggie_smalls, sprites.dungeon.hazardWater)
tiles.placeOnRandomTile(candice, sprites.vehicle.roadVertical)
tiles.placeOnRandomTile(small, sprites.dungeon.doorClosedNorth)
tiles.placeOnRandomTile(dez, sprites.vehicle.roadTurn2)
tiles.placeOnRandomTile(chris, sprites.dungeon.stairLadder)
controller.moveSprite(chris, 100, 100)
music.playMelody("C5 C D E A G F B ", 69)
